name: Run Python Test
on:
  push:
jobs:
  build:
    name: Set up environment
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/chechout@v2
    -name: Run my python
      run: |
        python3 test.py
