name: Run Python Test
on:
  push:
jobs:
  build:
    name: Set up environment
    runs-on: ubuntu-lastest
    steps: 
    - uses: actions/chechout@v2
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
    -name: Run my python
      run: |
        python3 test.py
