name: Run Python Test
on:
  #push:
  schedule:
  - cron: "0 0 * * *"
jobs:
  build:
    name: Set up environment
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Run my python
      run: |
        python3 test.py
